name: Build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup chroot
      run: ./docker.sh setup_chroot

    - name: Chroot and setup gentoo
      run: ./docker.sh setup_build

    - name: Build system
      run: ./docker.sh build
      
    - name: Cleanup root
      run: ./docker.sh clean

    - name: Upload docker image
      run: ./docker.sh upload
